import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import axios from 'axios';
import { Leaf, LayoutDashboard, Sprout, FlaskConical, PackageOpen, RefreshCw, Trash2, LogOut } from 'lucide-react';
import './styles.css';

const api = axios.create({ baseURL: '/api' });
const nav = [
  ['Dashboard', LayoutDashboard], ['Plants', Sprout], ['Media', FlaskConical],
  ['Mother Bottles', PackageOpen], ['Subcultures', RefreshCw], ['Discards', Trash2]
];

function Login({ onLogin }) {
  const [username,setUsername]=useState('admin'), [password,setPassword]=useState('ChangeMe123!'), [error,setError]=useState('');
  async function submit(e){ e.preventDefault(); const token=btoa(`${username}:${password}`); api.defaults.headers.common.Authorization=`Basic ${token}`;
    try { const {data}=await api.get('/me'); sessionStorage.setItem('labAuth',token); onLogin(data); } catch { setError('Username or password is incorrect.'); }
  }
  return <main className="login"><form className="login-card" onSubmit={submit}><div className="brand-mark"><Leaf/></div><p className="eyebrow">NATURAL FOLIAGE</p><h1>Lab Management</h1><p className="muted">Sign in to manage cultures and inventory.</p>{error&&<div className="error">{error}</div>}<label>Username<input value={username} onChange={e=>setUsername(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label><button>Sign in</button><small>Development login is pre-filled for the first run.</small></form></main>
}

function Dashboard(){const [d,setD]=useState({}); useEffect(()=>{api.get('/dashboard').then(r=>setD(r.data))},[]); const cards=[['Registered plants',d.plants,'plant'],['Active mothers',d.activeMothers,'mother'],['Active subcultures',d.activeSubcultures,'culture'],['Total discards',d.discards,'discard']]; return <><header><p className="eyebrow">OVERVIEW</p><h1>Laboratory dashboard</h1><p className="muted">A quick view of today’s tissue-culture inventory.</p></header><section className="cards">{cards.map(([l,v,c])=><article className={`stat ${c}`} key={l}><span>{l}</span><strong>{v??'—'}</strong></article>)}</section><section className="panel"><h2>Welcome to your new full-stack project</h2><p>Start by registering plants and media. Then create mother bottles, track subcultures, and record discards.</p><div className="flow"><b>Plant</b><i>→</i><b>Mother bottle</b><i>→</i><b>Subculture</b><i>→</i><b>Rooting / discard</b></div></section></>}

const configs={
 Plants:{url:'/plants',title:'Plant catalogue',fields:[['code','Plant code'],['name','Plant name'],['variety','Variety'],['description','Description']]},
 Media:{url:'/media',title:'Media compositions',fields:[['code','Media code'],['basalMedia','Basal media'],['hormones','Hormones'],['ph','pH','number'],['agar','Agar (g/L)','number']]}
};
function CrudPage({type,user}){const c=configs[type], empty=Object.fromEntries(c.fields.map(f=>[f[0],''])); const [rows,setRows]=useState([]),[form,setForm]=useState(empty),[error,setError]=useState(''); const load=()=>api.get(c.url).then(r=>setRows(r.data)); useEffect(load,[type]); async function save(e){e.preventDefault();setError('');try{await api.post(c.url,form);setForm(empty);load()}catch(e){setError(e.response?.data?.message||'Could not save this record.')}} async function remove(id){if(confirm('Delete this record?')){await api.delete(`${c.url}/${id}`);load()}} return <><header><p className="eyebrow">MASTER DATA</p><h1>{c.title}</h1></header><section className="split"><form className="panel form" onSubmit={save}><h2>Add new</h2>{error&&<div className="error">{error}</div>}{c.fields.map(([key,label,t])=><label key={key}>{label}<input type={t||'text'} step="any" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} required={key==='code'||key==='name'||key==='basalMedia'}/></label>)}<button>Save {type==='Plants'?'plant':'media'}</button></form><section className="panel table-wrap"><table><thead><tr>{c.fields.slice(0,3).map(f=><th key={f[0]}>{f[1]}</th>)}<th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{c.fields.slice(0,3).map(f=><td key={f[0]}>{r[f[0]]||'—'}</td>)}<td>{user.role==='ADMIN'&&<button className="icon danger" onClick={()=>remove(r.id)}><Trash2 size={16}/></button>}</td></tr>)}{!rows.length&&<tr><td colSpan="4" className="empty">No records yet.</td></tr>}</tbody></table></section></section></>}

function SimpleList({type}){const paths={'Mother Bottles':'/mother-bottles','Subcultures':'/subcultures','Discards':'/discards'}; const [rows,setRows]=useState([]);useEffect(()=>{api.get(paths[type]).then(r=>setRows(r.data))},[type]);return <><header><p className="eyebrow">LAB WORKFLOW</p><h1>{type}</h1><p className="muted">The first MVP exposes the workflow data; registration forms and barcode printing are the next learning milestone.</p></header><section className="panel table-wrap"><table><thead><tr><th>Barcode</th><th>Plant / reason</th><th>Technician</th><th>Status / date</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.barcode}</b></td><td>{r.plant?.name||r.reason||'—'}</td><td>{r.technician}</td><td><span className="badge">{r.status||r.discardedDate}</span></td></tr>)}{!rows.length&&<tr><td colSpan="4" className="empty">No records yet.</td></tr>}</tbody></table></section></>}

function App(){const token=sessionStorage.getItem('labAuth'); if(token)api.defaults.headers.common.Authorization=`Basic ${token}`; const [user,setUser]=useState(null),[page,setPage]=useState('Dashboard'),[loading,setLoading]=useState(!!token); useEffect(()=>{if(token)api.get('/me').then(r=>setUser(r.data)).catch(()=>sessionStorage.removeItem('labAuth')).finally(()=>setLoading(false))},[]); if(loading)return <div className="loading">Loading…</div>;if(!user)return <Login onLogin={setUser}/>; let content=page==='Dashboard'?<Dashboard/>:configs[page]?<CrudPage type={page} user={user}/>:<SimpleList type={page}/>; return <div className="shell"><aside><div className="logo"><Leaf/><div><b>Natural Foliage</b><span>LAB SYSTEM</span></div></div><nav>{nav.map(([label,Icon])=><button className={page===label?'active':''} onClick={()=>setPage(label)} key={label}><Icon size={19}/>{label}</button>)}</nav><div className="profile"><div className="avatar">{user.fullName[0]}</div><div><b>{user.fullName}</b><span>{user.role}</span></div><button className="icon" onClick={()=>{sessionStorage.clear();setUser(null)}}><LogOut size={17}/></button></div></aside><main className="content">{content}</main></div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
