import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import axios from 'axios';
import { Leaf, LayoutDashboard, Sprout, FlaskConical, PackageOpen, RefreshCw, Trash2, LogOut, Users, BadgeDollarSign } from 'lucide-react';
import './styles.css';
import './staff.css';
import './dashboard.css';

const api = axios.create({ baseURL: '/api' });
const nav = [
  ['Dashboard', LayoutDashboard], ['Plants', Sprout], ['Media', FlaskConical],
  ['Mother Bottles', PackageOpen], ['Subcultures', RefreshCw], ['Discards', Trash2], ['Price List', BadgeDollarSign], ['Staff', Users]
];
const accessOptions = [
  ['Dashboard','ACCESS_DASHBOARD'], ['Plants','ACCESS_PLANTS'], ['Media','ACCESS_MEDIA'],
  ['Mother Bottles','ACCESS_MOTHER_BOTTLES'], ['Subcultures','ACCESS_SUBCULTURES'], ['Discards','ACCESS_DISCARDS'], ['Price List','ACCESS_PRICE_LIST']
];
const hormoneOptions = ['BAP','2,4-D','2iP','IBA','IAA','Ascorbic Acid','Gibberellic Acid','Adenine Sulfate'];

function Login({ onLogin }) {
  const [username,setUsername]=useState('admin'), [password,setPassword]=useState('ChangeMe123!'), [error,setError]=useState('');
  async function submit(e){ e.preventDefault(); const token=btoa(`${username.trim()}:${password}`); api.defaults.headers.common.Authorization=`Basic ${token}`;
    try { const {data}=await api.get('/me'); sessionStorage.setItem('labAuth',token); onLogin(data); } catch { setError('Username or password is incorrect.'); }
  }
  return <main className="login"><form className="login-card" onSubmit={submit}><div className="brand-mark"><Leaf/></div><p className="eyebrow">NATURAL FOLIAGE</p><h1>Lab Management</h1><p className="muted">Sign in to manage cultures and inventory.</p>{error&&<div className="error">{error}</div>}<label>Username<input value={username} onChange={e=>setUsername(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label><button>Sign in</button><small>Development login is pre-filled for the first run.</small></form></main>
}

function OperationalTables(){
  const [details,setDetails]=useState({availablePlants:[],oldCultures:[]});
  useEffect(()=>{api.get('/dashboard/details').then(r=>setDetails(r.data))},[]);
  return <section className="dashboard-tables">
    <article className="panel table-wrap dashboard-table"><div className="table-heading"><div><p className="eyebrow">LIVE INVENTORY</p><h2>Available subculture plants</h2></div><span className="count-pill">{details.availablePlants.length} varieties</span></div><table><thead><tr><th>Plant code</th><th>Plant name</th><th>Multiply</th><th>Rooting</th><th>Total</th></tr></thead><tbody>{details.availablePlants.map(row=><tr key={row.plantCode}><td><b>{row.plantCode}</b></td><td>{row.plantName}</td><td>{row.multiply}</td><td>{row.rooting}</td><td><b>{row.total}</b></td></tr>)}{!details.availablePlants.length&&<tr><td colSpan="5" className="empty">No active subculture plants yet.</td></tr>}</tbody></table></article>
    <article className="panel table-wrap dashboard-table warning-table"><div className="table-heading"><div><p className="eyebrow warning">ATTENTION REQUIRED</p><h2>Subculture bottles older than 6 weeks</h2></div><span className="count-pill warning">{details.oldCultures.length} groups</span></div><table><thead><tr><th>Week</th><th>Code</th><th>Variety</th><th>Bottles</th><th>Total plants</th><th>Age</th></tr></thead><tbody>{details.oldCultures.map((row,index)=><tr key={`${row.plantCode}-${row.subcultureWeek}-${index}`}><td>{row.subcultureWeek||'—'}</td><td><b>{row.plantCode}</b></td><td>{row.variety}</td><td>{row.bottles}</td><td>{row.totalPlants}</td><td><span className="age-alert">{row.ageWeeks} weeks</span></td></tr>)}{!details.oldCultures.length&&<tr><td colSpan="6" className="empty healthy">No overdue subculture bottles.</td></tr>}</tbody></table></article>
  </section>
}

function Dashboard({user}){const [d,setD]=useState({}); useEffect(()=>{api.get('/dashboard').then(r=>setD(r.data))},[]); const tech=user.role==='TECHNICIAN'; const cards=[['Registered plants',d.plants,'plant'],['Active mothers',d.activeMothers,'mother'],['Active subcultures',d.activeSubcultures,'culture'],['Total discards',d.discards,'discard']]; return <><header><p className="eyebrow">{tech?'MY WORKSPACE':'OVERVIEW'}</p><h1>{tech?'Technician dashboard':'Laboratory dashboard'}</h1><p className="muted">{tech?`${user.fullName} · ${user.employeeId} · ${user.labSection}`:'A quick view of today’s tissue-culture inventory.'}</p></header><section className="cards">{cards.map(([l,v,c])=><article className={`stat ${c}`} key={l}><span>{l}</span><strong>{v??'—'}</strong></article>)}</section>{tech?<section className="panel technician-welcome"><div><span className="badge">ACTIVE TECHNICIAN</span><h2>Your assigned section: {user.labSection}</h2><p>Use the menu to record and review work for your laboratory section. Every saved operation will be linked to your profile.</p></div><div className="employee-card"><small>EMPLOYEE ID</small><strong>{user.employeeId}</strong><small>ROLE</small><strong>{user.role}</strong></div></section>:<section className="panel"><h2>Laboratory management overview</h2><p>Register plants and media, manage staff, create mother bottles, track subcultures, and record discards.</p><div className="flow"><b>Plant</b><i>→</i><b>Mother bottle</b><i>→</i><b>Subculture</b><i>→</i><b>Rooting / discard</b></div></section>}<OperationalTables/></>}

function HormoneMultiSelect({value,onChange}){
  const escaped=option=>option.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
  const selected=hormoneOptions.filter(option=>new RegExp(`(^|[;,]\\s*)(?:${escaped(option)})(?:\\s|;|$)`).test(value||''));
  const quantity=option=>(value||'').match(new RegExp(`${escaped(option)}\\s+([0-9]*\\.?[0-9]+)\\s*mg/L`,'i'))?.[1]||'';
  function serialize(options,changedOption,changedQuantity){return options.map(option=>{const amount=option===changedOption?changedQuantity:quantity(option);return amount?`${option} ${amount} mg/L`:option}).join('; ')}
  function toggle(option){onChange(selected.includes(option)?serialize(selected.filter(item=>item!==option)):serialize([...selected,option]))}
  function setQuantity(option,amount){onChange(serialize(selected,option,amount))}
  return <details className="multi-select"><summary>{selected.length?`${selected.length} selected`:'Select one or more hormones'}</summary><div className="multi-select-menu">{hormoneOptions.map(option=><div className={`hormone-row ${selected.includes(option)?'selected':''}`} key={option}><label><input type="checkbox" checked={selected.includes(option)} onChange={()=>toggle(option)}/><span>{option}</span></label>{selected.includes(option)&&<div className="quantity-field"><input aria-label={`${option} quantity`} type="number" min="0" step="0.001" placeholder="0.000" value={quantity(option)} onChange={e=>setQuantity(option,e.target.value)} required/><span>mg/L</span></div>}</div>)}</div>{selected.length>0&&<div className="selected-values">{selected.map(option=><span key={option}>{option}{quantity(option)?` · ${quantity(option)} mg/L`:' · quantity required'}</span>)}</div>}</details>
}

const configs={
 Plants:{url:'/plants',title:'Plant catalogue',buttonLabel:'plant',fields:[['code','Plant code'],['name','Plant name'],['variety','Variety'],['description','Description']]},
 Media:{url:'/media',title:'Media compositions',buttonLabel:'media',fields:[['code','Media code'],['basalMedia','Basal media'],['hormones','Hormones'],['ph','pH','number'],['agar','Agar (g/L)','number']]},
 'Price List':{url:'/price-list',title:'Plant price list',buttonLabel:'price',fields:[['plantCode','Plant code'],['varietyName','Variety name'],['price','Unit price (LKR)','number']]}
};
function CrudPage({type,user}){const c=configs[type], empty=Object.fromEntries(c.fields.map(f=>[f[0],''])); const [rows,setRows]=useState([]),[form,setForm]=useState(empty),[error,setError]=useState(''); const load=()=>api.get(c.url).then(r=>setRows(r.data)); useEffect(()=>{load()},[type]); async function save(e){e.preventDefault();setError('');try{await api.post(c.url,form);setForm(empty);load()}catch(e){setError(e.response?.data?.message||'Could not save this record.')}} async function remove(id){if(confirm('Delete this record?')){await api.delete(`${c.url}/${id}`);load()}} return <><header><p className="eyebrow">MASTER DATA</p><h1>{c.title}</h1></header><section className="split"><form className="panel form" onSubmit={save}><h2>Add new</h2>{error&&<div className="error">{error}</div>}{c.fields.map(([key,label,t])=><label key={key}>{label}{type==='Media'&&key==='hormones'?<HormoneMultiSelect value={form.hormones} onChange={hormones=>setForm({...form,hormones})}/>:<input type={t||'text'} step="any" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} required />}</label>)}<button>Save {c.buttonLabel}</button></form><section className="panel table-wrap"><table><thead><tr>{c.fields.slice(0,3).map(f=><th key={f[0]}>{f[1]}</th>)}<th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{c.fields.slice(0,3).map(f=><td key={f[0]}>{r[f[0]]??'—'}</td>)}<td>{user.role==='ADMIN'&&<button className="icon danger" onClick={()=>remove(r.id)}><Trash2 size={16}/></button>}</td></tr>)}{!rows.length&&<tr><td colSpan="4" className="empty">No records yet.</td></tr>}</tbody></table></section></section></>}

function SimpleList({type}){const paths={'Mother Bottles':'/mother-bottles','Subcultures':'/subcultures','Discards':'/discards'}; const [rows,setRows]=useState([]);useEffect(()=>{api.get(paths[type]).then(r=>setRows(r.data))},[type]);return <><header><p className="eyebrow">LAB WORKFLOW</p><h1>{type}</h1><p className="muted">The first MVP exposes the workflow data; registration forms and barcode printing are the next learning milestone.</p></header><section className="panel table-wrap"><table><thead><tr><th>Barcode</th><th>Plant / reason</th><th>Technician</th><th>Status / date</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.barcode}</b></td><td>{r.plant?.name||r.reason||'—'}</td><td>{r.technician}</td><td><span className="badge">{r.status||r.discardedDate}</span></td></tr>)}{!rows.length&&<tr><td colSpan="4" className="empty">No records yet.</td></tr>}</tbody></table></section></>}

function StaffPage(){
  const initial={employeeId:'',fullName:'',username:'',password:'',role:'TECHNICIAN',labSection:'Subculture',active:true,permissions:['ACCESS_DASHBOARD']};
  const [staff,setStaff]=useState([]),[form,setForm]=useState(initial),[error,setError]=useState('');
  const load=()=>api.get('/users').then(r=>setStaff(r.data));
  useEffect(()=>{load()},[]);
  async function save(e){e.preventDefault();setError('');try{await api.post('/users',form);setForm(initial);load()}catch(e){setError(e.response?.data?.message||'Could not create staff account.')}}
  async function toggle(person){try{await api.patch(`/users/${person.id}/status`,{active:!person.active});load()}catch(e){setError(e.response?.data?.message||'Could not change account status.')}}
  async function updateAccess(person,permission){const current=person.permissions||[];const permissions=current.includes(permission)?current.filter(item=>item!==permission):[...current,permission];try{await api.patch(`/users/${person.id}/permissions`,{permissions});load()}catch(e){setError(e.response?.data?.message||'Could not change user access.')}}
  function changeAccess(permission){setForm({...form,permissions:form.permissions.includes(permission)?form.permissions.filter(item=>item!==permission):[...form.permissions,permission]})}
  return <><header><p className="eyebrow">ADMINISTRATION</p><h1>Staff & access control</h1><p className="muted">Create individual accounts and choose exactly which parts of the system they can use.</p></header><section className="split staff-layout"><form className="panel form" onSubmit={save}><h2>Create staff account</h2>{error&&<div className="error">{error}</div>}<label>Employee ID<input value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})} required /></label><label>Full name<input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} required /></label><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} required /></label><label>Temporary password<input type="password" minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required /></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="TECHNICIAN">Technician</option><option value="ADMIN">Administrator (full access)</option></select></label><label>Lab section<select value={form.labSection} onChange={e=>setForm({...form,labSection:e.target.value})}><option>Subculture</option><option>Media Preparation</option><option>Mother Culture</option><option>Rooting</option><option>Administration</option></select></label>{form.role==='TECHNICIAN'&&<fieldset className="access-picker"><legend>System access</legend><p>Select the tabs this user is allowed to open.</p><div>{accessOptions.map(([label,permission])=><label className="access-option" key={permission}><input type="checkbox" checked={form.permissions.includes(permission)} onChange={()=>changeAccess(permission)}/><span>{label}</span></label>)}</div></fieldset>}<button>Create account</button></form><section className="panel table-wrap"><table><thead><tr><th>Employee</th><th>Username</th><th>Role / section</th><th>Access</th><th>Status</th><th></th></tr></thead><tbody>{staff.map(person=><tr key={person.id}><td><b>{person.fullName}</b><small className="cell-sub">{person.employeeId}</small></td><td>{person.username}</td><td>{person.role}<small className="cell-sub">{person.labSection||'—'}</small></td><td><div className="permission-list">{person.role==='ADMIN'?<span className="permission-tag admin-access">Full access</span>:accessOptions.map(([label,permission])=><label className="permission-toggle" key={permission}><input type="checkbox" checked={(person.permissions||[]).includes(permission)} onChange={()=>updateAccess(person,permission)}/><span>{label}</span></label>)}</div></td><td><span className={`badge ${person.active?'':'inactive'}`}>{person.active?'Active':'Inactive'}</span></td><td><button className="secondary compact" onClick={()=>toggle(person)}>{person.active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></section></section></>
}

function App(){const token=sessionStorage.getItem('labAuth'); if(token)api.defaults.headers.common.Authorization=`Basic ${token}`; const [user,setUser]=useState(null),[page,setPage]=useState(null),[loading,setLoading]=useState(!!token); useEffect(()=>{if(token)api.get('/me').then(r=>setUser(r.data)).catch(()=>sessionStorage.removeItem('labAuth')).finally(()=>setLoading(false))},[]); if(loading)return <div className="loading">Loading…</div>;if(!user)return <Login onLogin={setUser}/>; const allowed=new Set(user.permissions||[]); const visibleNav=nav.filter(([label])=>user.role==='ADMIN'||(label!=='Staff'&&allowed.has(accessOptions.find(item=>item[0]===label)?.[1]))); const activePage=page&&visibleNav.some(([label])=>label===page)?page:visibleNav[0]?.[0]; if(!activePage)return <div className="loading">Your account has no system access. Ask an administrator to assign access.</div>; let content=activePage==='Dashboard'?<Dashboard user={user}/>:activePage==='Staff'?<StaffPage/>:configs[activePage]?<CrudPage type={activePage} user={user}/>:<SimpleList type={activePage}/>; return <div className="shell"><aside><div className="logo"><Leaf/><div><b>Natural Foliage</b><span>LAB SYSTEM</span></div></div><nav>{visibleNav.map(([label,Icon])=><button className={activePage===label?'active':''} onClick={()=>setPage(label)} key={label}><Icon size={19}/>{label}</button>)}</nav><div className="profile"><div className="avatar">{user.fullName[0]}</div><div><b>{user.fullName}</b><span>{user.role}</span></div><button className="icon" onClick={()=>{sessionStorage.clear();setUser(null)}}><LogOut size={17}/></button></div></aside><main className="content">{content}</main></div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
